# Generated by Django 4.1.7 on 2023-06-08 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MetaText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=255, unique=True, verbose_name="Key"),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=100, verbose_name="Active"),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="If False, it will return 404 Response",
                        verbose_name="Active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meta Text",
                "verbose_name_plural": "Meta Texts",
            },
        ),
        migrations.CreateModel(
            name="TextContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_contents",
                        to="plugins.metatext",
                        verbose_name="Plugin",
                    ),
                ),
            ],
        ),
    ]
