# Generated by Django 4.1.7 on 2023-06-21 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="name",
        ),
        migrations.AddField(
            model_name="myproject",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(
                max_length=254,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Email must be entered in the format: `abc@abc.com|net|org|info`.",
                        regex="^[A-z0-9\\.]+@[A-z0-9]+\\.(com|net|org|info)$",
                    )
                ],
                verbose_name="Email Address",
            ),
        ),
    ]
