# Generated by Django 4.1.7 on 2023-06-22 07:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_remove_contact_name_myproject_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myproject",
            name="slug",
        ),
        migrations.AlterField(
            model_name="myproject",
            name="description",
            field=ckeditor.fields.RichTextField(
                blank=True, help_text="Not Required", verbose_name="Description"
            ),
        ),
    ]
