# Generated by Django 4.1.7 on 2023-06-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_remove_myproject_slug_alter_myproject_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="source",
            field=models.ManyToManyField(related_name="posts", to="base.postsource"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                default="",
                help_text="Required",
                max_length=255,
                unique=True,
                verbose_name="Title",
            ),
        ),
    ]
